### ISSUE TITLE
Memory structured parsing failed

### ISSUE THREAD

**Issue by beastoin** [BasedHardware/omi#1477]
<img width="1443" alt="Screenshot 2024-12-05 at 05 41 38" src="https://github.com/user-attachments/assets/bc9eb64a-1303-4cd7-a117-8093bb0b904f">

trace: https://us5.datadoghq.com/error-tracking/issue/8b6fa510-a810-11ef-ab3b-da7ad0900000?query=env%3Aprod%20service%3Abackend&from_ts=1733265581933&to_ts=1733351981933&live=true

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/output_parsers/json.py", line 83, in parse_result
    return parse_json_markdown(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/utils/json.py", line 144, in parse_json_markdown
    return _parse_json(json_str, parser=parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/utils/json.py", line 160, in _parse_json
    return parser(json_str)
           ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/utils/json.py", line 118, in parse_partial_json
    return json.loads(s, strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 113 (char 170)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dd_tracer/python/ddtrace/contrib/internal/langchain/patch.py", line 804, in traced_lcel_runnable_sequence
    final_output = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3024, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 193, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1927, in _call_with_config
    context.run(
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 396, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/output_parsers/base.py", line 194, in <lambda>
    lambda inner_input: self.parse_result(
                        ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/output_parsers/pydantic.py", line 72, in parse_result
    raise e
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/output_parsers/pydantic.py", line 67, in parse_result
    json_object = super().parse_result(result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/langchain_core/output_parsers/json.py", line 86, in parse_result
    raise OutputParserException(msg, llm_output=text) from e
langchain_core.exceptions.OutputParserException: Invalid json output: {
    "title": "Celebrity Reactions and Upcoming Events",
    "overview": "The conversation discusses the reactions of various celebrities to Kendrick Lamar's new song, "Not Like Us," with comments from
    ```

**Comment by SwapnilSonker** [comment]
@beastoin can you tell how can i reproduce this error ?
