### ISSUE TITLE
when I print "npm start", it makes error, if anyone can give me some advice?

### ISSUE THREAD

**Issue by xuyixiO** [BasedHardware/Omi#584]
SyntaxError: Unexpected token ?
/home/xuyixiao/桌面/Omi/OpenGlass/node_modules/@expo/config/build/Config.js:147
  } = config.expo ?? config;
                   ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/xuyixiao/桌面/Omi/OpenGlass/node_modules/@expo/config/build/index.js:15:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! find-anything-tester@1.0.0 start: `expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the find-anything-tester@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xuyixiao/.npm/_logs/2024-08-11T04_21_46_507Z-debug.log

**Comment by xuyixiO** [comment]
this error is for openglass program. i'm feel very grateful if anyone can give me some advice

**Comment by josancamon19** [comment]
Openglass works with the flutter app, openglass redux app will be removed soon, and is no longer maintained.
